name: Rust

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-mac:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install latest rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-apple-darwin
        default: true
        override: true

    - name: Build for Mac
      run: cargo build --all --release && strip target/release/server && mv target/release/server target/release/server_darwin
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          target/release/server_darwin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
